configuracion:
    
    servidor:
#        appserver: unicorn
#        puerto: 3000
#        binding: localhost
#        entorno: development
#        worker_processes: 2
#        timeout: 120

        ## Basado en la configuraciín del mailer de Diaspora
        mail: ## Section
  
            ## First you need to enable it.
            enable: true
    
            ## Sender address used in mail sent by Diaspora
            sender_address: 'jaedns@gmail.com'
            
            ## This selects which mailer should be used. Use 'smtp' for a smtp
            ## connection, 'sendmail' to use the sendmail binary or
            ## 'messagebus' to use the messagebus service.
            method: 'smtp'
            
            ## Ignore if method isn't 'smtp'
            smtp: ## Section

                ## Host and port of the smtp server handling outgoing mail.
                ## This should match the common name of the certificate sent by
                ## the SMTP server, if it sends one. (default port=587)
                host: 'smtp.strato.de'
                port: 143
                
                ## Authentication required to send mail (default='plain')
                ## Use one of 'plain', 'login' or 'cram_md5'. Use 'none'
                ## if server does not support authentication.
                authentication: 'plain'
                
                ## Credentials to log in to the SMTP server
                ## May be necessary if authentication is not 'none'.
                username: 'inademus@alcaldiadecumana.org'
                password: '1N4D3MU5'
                
                ## Automatically enable TLS (default=true)
                ## Leave this commented out if authentication is set to 'none'.
                starttls_auto: true
                
                ## The domain for the HELO command, if needed
                domain: 'alcaldiadecumana.org'
                
                ## OpenSSL verify mode used when connecting to a SMTP server with TLS
                ## Set this to 'none' if you have a self-signed certificate. Possible
                ## values: 'none', 'peer', 'client_once', 'fail_if_no_peer_cert'.
                #openssl_verify_mode: 'none'
            
            ## Ignore if method isn't 'sendmail'
            sendmail: ## Section

                ## The path to the sendmail binary (default='/usr/sbin/sendmail')
                #location: '/usr/sbin/sendmail'
                
                ## Use exim and sendmail (default=false)
                #exim_fix: false
            
            ## Ignore if method isn't 'messagebus'
            #message_bus_api_key: 'abcdef'

    aplicacion:
        host: 12k.alcaldiadecumana.org
        url: http://12k.alcaldiadecumana.org
        titulo: 'Carrera 12K Cumaná 500 - 2da Edici&oacute;n'
#        descripcion: 'Sistema de información Gerencial Libre'
#        favicon_src: '/favicon.png'
        banner_src: '/banner.jpg'
#        logo_src: ''
        resumen: '<div style="margin-bottom: 12px">República Bolivariana de Venezuela<br/>
                  Alcaldía Bolivariana del Municipio Sucre<br/>
                    <span style="font-weight: bold; font-size: 16px">Instituto Autónomo de Deporte del Municipio Sucre</span><br/>
                    G-20004107-2</div>
                  <div style="text-align: left;line-height: 18px;">
                    Dirección: <b>Cumaná, Av. Bermudez, arriba del modulo de la Policia Municipal.</b><br/>
                    Horarios de atención al público: <b>lunes a viernes, de 8:30 am a 12:00 pm y de 1:00 pm a 5:00 pm.</b><br/>
                    Teléfonos: <b>0426-9824832 / 0293-6447328</b><br/>
                    Correo electrónico: <b>inademuscumana@gmail.com</b><br/></div>
                  <div style="margin-top: 12px; text-align: right;">
                    <a href="https://www.facebook.com/inademus.cumana.3" target="_blank" title="INADEMUS en Facebook"><i class="fa fa-facebook-square fa-5x"></i></a>
                    &nbsp; &nbsp;
                    <a href="https://www.twitter.com/INADEMUSOFICIAL" target="_blank" title="INADEMUS en Twitter"><i class="fa fa-twitter-square fa-5x"></i></a>
                  </div>
                  <div style="margin-top: 12px; font-weight: bold">
                    <!--[if lte IE 8]><span style="filter: FlipH; -ms-filter: "FlipH"; display: inline-block;"><![endif]-->
                    <span style="-moz-transform: scaleX(-1); -o-transform: scaleX(-1); -webkit-transform: scaleX(-1); transform: scaleX(-1); display: inline-block;">
                        &copy;
                    </span>
                    <!--[if lte IE 8]></span><![endif]-->
                    2016 INADEMUS</div>'

        archivos:
            directorio: <%=ENV[:OPENSHIFT_DATA_DIR]%>'uploads/files'
            papelera: <%=ENV[:OPENSHIFT_DATA_DIR]%>'uploads/trash/files'
#            
        posts:
            directorio: <%=ENV[:OPENSHIFT_DATA_DIR]%>'uploads/posts'
            papelera: <%=ENV[:OPENSHIFT_DATA_DIR]%>'uploads/trash/posts'
#            tamanio_resumen: 512
#            por_pagina: 6

#        Se implementan comentarios con Disqus
        #disqus:
            #enable: true
            #shortname: 'iambomberoscumana'

development:

production:
